const copy = {
  en: {
    "nav.home":"Home","nav.services":"Builds","nav.run":"The Run","nav.setup":"Build your setup","nav.garage":"The Garage","nav.cross":"Cross-Border","nav.rescue":"Rebuild","nav.pit":"Pit Crew","nav.contact":"Contact",
    "hero.tagline":"YOUR BUSINESS. FULL THROTTLE.","hero.sub":"Websites · E-commerce · Multilingual · Digital Systems","hero.start":"START YOUR BUILD","hero.garage":"ENTER THE GARAGE","langs.interfaceLabel":"VIEW LAUNCH CTRL IN","langs.buildLabel":"WE BUILD CLIENT WEBSITES IN","langs.expand":"All six languages are available for client builds. Final commercial copy receives human/native QA where required before publication.",
    "manifesto":"Different businesses shouldn't look like they came from the same template.","manifestoStrong":"WE DON'T SELL TEMPLATES. WE BUILD FOR THE BUSINESS.","run.kicker":"THE RUN / PROCESS","run.title":"From first brief to live system.","run.brief.title":"BRIEF","run.brief.body":"We get the business, audience, goals, constraints and must-haves straight.","run.direction.title":"DIRECTION","run.direction.body":"We define structure, visual language, content logic and the conversion route.","run.build.title":"BUILD","run.build.body":"The real responsive product is built — not a static mockup pretending to be a website.","run.test.title":"TEST","run.test.body":"Mobile, content, forms, navigation, accessibility basics and production behaviour are checked.","run.launch.title":"LAUNCH","run.launch.body":"Production deployment, domain handoff and the final release checklist.","run.pit.title":"PIT CREW","run.pit.body":"Optional ongoing care for changes, additions, monitoring and future improvements.","dyno.complexity":"BUILD COMPLEXITY","dyno.reach":"MARKET REACH","dyno.load":"SYSTEM LOAD",
    "services.kicker":"SERVICES / BUILDS","services.title":"Choose the machine. Then spec it for your business.","services.quickstart":"Compact website, landing page or focused small-business launch.","services.full":"Custom business website shaped around your offer, audience and workflow.","services.cross":"Multilingual architecture, localization and market-ready adaptation.","services.rebuild":"Rescue, redesign and performance cleanup for websites that stopped working for the business.","services.shop":"E-commerce built around products, trust, checkout clarity and future expansion.","services.fullspec":"Complex custom builds, integrations, automation and advanced functionality.","services.pit":"Monthly website care, monitoring, updates, improvements and support.",
    "setup.kicker":"BUILD YOUR SETUP","setup.title":"Configure a realistic starting spec.","setup.estimate":"ESTIMATED BUILD","setup.note":"Planning estimate — not a fixed tariff. Final scope and commercial quote follow a real project review.","setup.cta":"REQUEST FINAL QUOTE",
    "garage.title":"Four businesses. Four completely different builds.","garage.statement":"Same studio. Different business logic, visual language and customer journey.",
    "multi.kicker":"SPEAK TO THE WHOLE GRID.","multi.title":"Your business, understood everywhere.","multi.core":"We build and localize websites in English, Romanian, French, German, Italian and Russian.","multi.expansion":"Final commercial copy is reviewed where required before publication. Native/human QA is a quality-control step, not a language limitation.","multi.body":"We build the architecture for translated navigation, metadata, copy adaptation, language-specific UX and localization — not just a language dropdown.","multi.qa":"Language delivery is scoped per project, so each market gets a deliberate experience rather than a machine-translated duplicate.",
    "rescue.title":"YOUR WEBSITE IS LOSING HORSEPOWER.","rescue.body":"Get a free 5-minute diagnosis across mobile, design, copy, conversion, performance, multilingual readiness and accessibility basics.","rescue.cta":"GET A REBUILD QUOTE","rebuildDemo.title":"DRAG IT FROM LOST TO LAUNCH-READY.","rebuildDemo.beforeHeadline":"EVERYTHING COMPETES.","rebuildDemo.beforeBody":"Weak hierarchy · buried CTA · generic sections · no clear route.","rebuildDemo.afterHeadline":"ONE JOB. CLEAR ROUTE.","rebuildDemo.afterBody":"Distinct direction · strong hierarchy · deliberate conversion · mobile-first structure.","rebuildDemo.range":"REBUILD INTENSITY",
    "pit.body":"A website is not a one-time poster. We keep it updated, monitored and useful after launch.","included.kicker":"WHAT YOU ACTUALLY GET","included.title":"Not just pages. A working digital system.","included.responsive":"Designed to work across modern phones, tablets and desktop screens.","included.performance":"Lean architecture, optimized assets and sensible motion from the start.","included.seo":"Metadata, crawlability and page structure prepared for search.","included.accessibility":"Keyboard, semantics, contrast and reduced-motion considerations built in.","included.conversion":"Clear routes to contact, book, buy, enquire or take the next business action.","included.deployment":"A production-ready release with hosting/deployment setup appropriate to the build.","included.analytics":"Measurement hooks can be prepared so the site can tell you what users actually do.","included.expansion":"The build is structured so future pages, markets and functionality do not require starting over.","impact.kicker":"BUSINESS IMPACT / DESIGN TARGETS","impact.title":"Built to move the business, not decorate a browser tab.","impact.disclaimer":"These are design and product targets — not guaranteed commercial outcomes. Results depend on the offer, traffic, market, operations and final scope.","impact.clarity.title":"CLARITY","impact.clarity.body":"Make the offer, audience and next step understandable fast.","impact.enquiries.title":"ENQUIRIES","impact.enquiries.body":"Remove friction between interest and a useful contact or quote request.","impact.action.title":"ACTION","impact.action.body":"Support the business action that matters: book, buy, apply, register or enquire.","impact.trust.title":"TRUST","impact.trust.body":"Use structure, copy and visual consistency to make the business easier to trust.","impact.reach.title":"REACH","impact.reach.body":"Prepare the experience for multiple languages and markets without duplicating chaos.","impact.growth.title":"GROWTH","impact.growth.body":"Build a system that can accept new pages, products, markets and functionality later.",
    "contact.title":"READY TO LAUNCH?","contact.body":"Tell us what the business needs. We will turn that into a clear build scope.","contact.consent":"I agree to be contacted about this project. No spam.","contact.cta":"TURN THE KEY","faq.kicker":"BEFORE YOU TURN THE KEY","faq.title":"The questions worth asking before a build starts.","faq.timeline.q":"How long does a website take?","faq.timeline.a":"It depends on scope. A focused build can move quickly; multilingual, e-commerce or integration-heavy projects need more time. The final timeline is agreed after scope review.","faq.ownership.q":"Do I own the website?","faq.ownership.a":"Ownership and handoff are defined in the final proposal. The goal is a clear, documented setup — not locking the client into mystery infrastructure.","faq.hosting.q":"Can you handle hosting and domains?","faq.hosting.a":"We can set up or guide hosting, deployment and domain configuration appropriate to the project. Third-party hosting and domain fees remain separate unless explicitly included.","faq.copy.q":"Can you write or rewrite the copy?","faq.copy.a":"Yes. Copywriting, restructuring and localization can be part of the build. Final language scope is agreed before work starts.","faq.languages.q":"Which languages can you build in?","faq.languages.a":"English, Romanian, French, German, Italian and Russian are all available for client builds. Final commercial copy receives human/native QA where required before publication.","faq.revisions.q":"How do revisions work?","faq.revisions.a":"Revision rounds and decision points are defined in the proposal so feedback stays useful and the project does not drift endlessly.","faq.shop.q":"Can you build e-commerce, booking or integrations?","faq.shop.a":"Yes. Those are scoped separately because complexity can vary dramatically depending on payments, catalogue size, providers, APIs and operational requirements.","faq.care.q":"What happens after launch?","faq.care.a":"You can keep the site independently or use PIT CREW for ongoing changes, additions, monitoring and support."
  },
  ro: {
    "nav.home":"Acasă","nav.services":"Builds","nav.run":"Proces","nav.setup":"Configurează","nav.garage":"Garajul","nav.cross":"Internațional","nav.rescue":"Rebuild","nav.pit":"Pit Crew","nav.contact":"Contact",
    "hero.tagline":"AFACEREA TA. LA TURAȚIE MAXIMĂ.","hero.sub":"Website-uri · E-commerce · Multilingv · Sisteme digitale","hero.start":"PORNEȘTE PROIECTUL","hero.garage":"INTRĂ ÎN GARAJ","langs.interfaceLabel":"VEZI LAUNCH CTRL ÎN","langs.buildLabel":"CONSTRUIM WEBSITE-URI PENTRU CLIENȚI ÎN","langs.expand":"Toate cele șase limbi sunt disponibile pentru proiectele clienților. Copy-ul comercial final primește verificare umană/native QA acolo unde este necesar înainte de publicare.",
    "manifesto":"Afaceri diferite nu ar trebui să arate de parcă au venit din același șablon.","manifestoStrong":"NU VINDEM ȘABLOANE. CONSTRUIM PENTRU AFACERE.","run.kicker":"THE RUN / PROCES","run.title":"De la primul brief la sistemul live.","run.brief.title":"BRIEF","run.brief.body":"Clarificăm afacerea, publicul, obiectivele, limitele și lucrurile obligatorii.","run.direction.title":"DIRECȚIE","run.direction.body":"Stabilim structura, limbajul vizual, logica de conținut și traseul de conversie.","run.build.title":"BUILD","run.build.body":"Construim produsul responsive real — nu un mockup static care se preface că este website.","run.test.title":"TEST","run.test.body":"Verificăm mobilul, conținutul, formularele, navigația, bazele accesibilității și comportamentul în producție.","run.launch.title":"LAUNCH","run.launch.body":"Deployment în producție, predarea domeniului și checklistul final de lansare.","run.pit.title":"PIT CREW","run.pit.body":"Îngrijire opțională după lansare pentru modificări, adăugiri, monitorizare și îmbunătățiri.","dyno.complexity":"COMPLEXITATE BUILD","dyno.reach":"ACOPERIRE PIEȚE","dyno.load":"ÎNCĂRCARE SISTEM",
    "services.kicker":"SERVICII / BUILDS","services.title":"Alege baza. Apoi o configurăm pentru afacerea ta.","services.quickstart":"Website compact, landing page sau lansare concentrată pentru o afacere mică.","services.full":"Website de business personalizat în jurul ofertei, publicului și fluxului tău de lucru.","services.cross":"Arhitectură multilingvă, localizare și adaptare pentru piețe internaționale.","services.rebuild":"Salvare, redesign și curățare de performanță pentru site-uri care nu mai lucrează pentru afacere.","services.shop":"E-commerce construit în jurul produselor, încrederii, unui checkout clar și extinderii viitoare.","services.fullspec":"Construcții complexe, integrări, automatizări și funcționalități avansate.","services.pit":"Îngrijire lunară, monitorizare, actualizări, îmbunătățiri și suport.",
    "setup.kicker":"CONFIGUREAZĂ-ȚI BUILD-UL","setup.title":"Construiește o configurație realistă de pornire.","setup.estimate":"ESTIMARE PROIECT","setup.note":"Estimare orientativă — nu tarif fix. Scope-ul și oferta comercială finală se stabilesc după analiza reală a proiectului.","setup.cta":"CERE OFERTA FINALĂ",
    "garage.title":"Patru afaceri. Patru construcții complet diferite.","garage.statement":"Același studio. Logică de business, limbaj vizual și customer journey diferite.",
    "multi.kicker":"VORBEȘTE CU TOATĂ GRILA.","multi.title":"Afacerea ta, înțeleasă peste tot.","multi.core":"Construim și localizăm website-uri în engleză, română, franceză, germană, italiană și rusă.","multi.expansion":"Copy-ul comercial final este verificat uman acolo unde este necesar înainte de publicare. Native/human QA este un standard de calitate, nu o limitare de limbă.","multi.body":"Construim arhitectura pentru navigație tradusă, metadata, adaptare de copy, UX specific limbii și localizare — nu doar un selector de limbă.","multi.qa":"Livrarea pe limbi se stabilește pentru fiecare proiect, astfel încât fiecare piață să primească o experiență intenționată, nu o copie tradusă automat.",
    "rescue.title":"SITE-UL TĂU PIERDE PUTERE.","rescue.body":"Primești o diagnoză gratuită de 5 minute pentru mobil, design, copy, conversie, performanță, pregătire multilingvă și bazele accesibilității.","rescue.cta":"CERE OFERTĂ DE REBUILD","rebuildDemo.title":"TRAGE-L DIN PIERDUT ÎN GATA DE LANSARE.","rebuildDemo.beforeHeadline":"TOTUL SE BATE CU TOTUL.","rebuildDemo.beforeBody":"Ierarhie slabă · CTA îngropat · secțiuni generice · niciun traseu clar.","rebuildDemo.afterHeadline":"UN SCOP. UN TRASEU CLAR.","rebuildDemo.afterBody":"Direcție distinctă · ierarhie puternică · conversie intenționată · structură mobile-first.","rebuildDemo.range":"INTENSITATE REBUILD",
    "pit.body":"Un website nu este un afiș făcut o singură dată. Îl păstrăm actualizat, monitorizat și util după lansare.","included.kicker":"CE PRIMEȘTI DE FAPT","included.title":"Nu doar pagini. Un sistem digital funcțional.","included.responsive":"Construit să funcționeze pe telefoane moderne, tablete și desktop.","included.performance":"Arhitectură lean, asset-uri optimizate și motion controlat din start.","included.seo":"Metadata, crawlability și structură de pagină pregătite pentru căutare.","included.accessibility":"Considerații de tastatură, semantică, contrast și reduced-motion integrate.","included.conversion":"Trasee clare către contact, rezervare, cumpărare, cerere de ofertă sau următoarea acțiune comercială.","included.deployment":"Lansare production-ready și configurare de hosting/deployment potrivită proiectului.","included.analytics":"Pregătire pentru măsurare, astfel încât site-ul să poată arăta ce fac utilizatorii în realitate.","included.expansion":"Structură gândită astfel încât paginile, piețele și funcțiile viitoare să nu ceară reconstruire de la zero.","impact.kicker":"IMPACT DE BUSINESS / OBIECTIVE DE DESIGN","impact.title":"Construit să miște afacerea, nu doar să decoreze un tab de browser.","impact.disclaimer":"Acestea sunt obiective de design și produs — nu rezultate comerciale garantate. Rezultatele depind de ofertă, trafic, piață, operațiuni și scope-ul final.","impact.clarity.title":"CLARITATE","impact.clarity.body":"Oferta, publicul și următorul pas trebuie înțelese rapid.","impact.enquiries.title":"CERERI","impact.enquiries.body":"Reducem fricțiunea dintre interes și un contact sau o cerere de ofertă utilă.","impact.action.title":"ACȚIUNE","impact.action.body":"Susținem acțiunea care contează pentru afacere: rezervare, cumpărare, aplicare, înscriere sau contact.","impact.trust.title":"ÎNCREDERE","impact.trust.body":"Folosim structură, copy și consistență vizuală pentru ca afacerea să inspire mai multă încredere.","impact.reach.title":"ACOPERIRE","impact.reach.body":"Pregătim experiența pentru mai multe limbi și piețe fără să multiplicăm haosul.","impact.growth.title":"CREȘTERE","impact.growth.body":"Construim un sistem care poate primi ulterior pagini, produse, piețe și funcționalități noi.",
    "contact.title":"GATA DE LANSARE?","contact.body":"Spune-ne de ce are nevoie afacerea. Noi transformăm asta într-un scope clar de proiect.","contact.consent":"Sunt de acord să fiu contactat(ă) despre acest proiect. Fără spam.","contact.cta":"PORNEȘTE MOTORUL","faq.kicker":"ÎNAINTE SĂ PORNEȘTI MOTORUL","faq.title":"Întrebările care merită puse înainte să înceapă un build.","faq.timeline.q":"Cât durează un website?","faq.timeline.a":"Depinde de scope. Un proiect concentrat poate avansa rapid; proiectele multilingve, e-commerce sau cu multe integrări cer mai mult timp. Calendarul final se stabilește după analiza scope-ului.","faq.ownership.q":"Website-ul îmi aparține?","faq.ownership.a":"Drepturile și predarea sunt definite în oferta finală. Obiectivul este un setup clar și documentat, nu blocarea clientului într-o infrastructură misterioasă.","faq.hosting.q":"Vă ocupați de hosting și domeniu?","faq.hosting.a":"Putem configura sau ghida hostingul, deployment-ul și domeniul potrivit proiectului. Costurile terților rămân separate dacă nu sunt incluse explicit.","faq.copy.q":"Puteți scrie sau rescrie textele?","faq.copy.a":"Da. Copywriting-ul, restructurarea și localizarea pot face parte din build. Limbile finale se stabilesc înainte să înceapă proiectul.","faq.languages.q":"În ce limbi puteți construi site-uri?","faq.languages.a":"Engleza, româna și franceza pot fi gestionate direct. Germana, italiana și rusa pot fi susținute prin arhitectură multilingvă și localizare, cu verificare umană/native QA înainte de publicare.","faq.revisions.q":"Cum funcționează reviziile?","faq.revisions.a":"Rundele de revizii și punctele de decizie sunt definite în ofertă, astfel încât feedbackul să rămână util și proiectul să nu se extindă la nesfârșit.","faq.shop.q":"Puteți construi e-commerce, booking sau integrări?","faq.shop.a":"Da. Se scopează separat, deoarece complexitatea poate varia mult în funcție de plăți, catalog, furnizori, API-uri și cerințe operaționale.","faq.care.q":"Ce se întâmplă după lansare?","faq.care.a":"Poți păstra site-ul independent sau poți folosi PIT CREW pentru modificări, adăugiri, monitorizare și suport."
  },
  fr: {
    "nav.home":"Accueil","nav.services":"Builds","nav.run":"Le parcours","nav.setup":"Configurer","nav.garage":"Le Garage","nav.cross":"International","nav.rescue":"Refonte","nav.pit":"Pit Crew","nav.contact":"Contact",
    "hero.tagline":"VOTRE ACTIVITÉ. PLEIN RÉGIME.","hero.sub":"Sites web · E-commerce · Multilingue · Systèmes digitaux","hero.start":"LANCER VOTRE PROJET","hero.garage":"ENTRER DANS LE GARAGE","langs.interfaceLabel":"VOIR LAUNCH CTRL EN","langs.buildLabel":"NOUS CRÉONS LES SITES CLIENTS EN","langs.expand":"DE / IT / RU sont disponibles pour les projets multilingues avec localisation et validation humaine/native QA avant publication.",
    "manifesto":"Des entreprises différentes ne devraient pas donner l'impression de sortir du même modèle.","manifestoStrong":"NOUS NE VENDONS PAS DES TEMPLATES. NOUS CONSTRUISONS POUR L'ENTREPRISE.","run.kicker":"THE RUN / PROCESSUS","run.title":"Du premier brief au système en ligne.","run.brief.title":"BRIEF","run.brief.body":"Nous clarifions l'activité, le public, les objectifs, les contraintes et les indispensables.","run.direction.title":"DIRECTION","run.direction.body":"Nous définissons la structure, le langage visuel, la logique éditoriale et le parcours de conversion.","run.build.title":"BUILD","run.build.body":"Nous construisons le vrai produit responsive — pas une maquette statique qui prétend être un site.","run.test.title":"TEST","run.test.body":"Mobile, contenu, formulaires, navigation, bases d'accessibilité et comportement en production sont vérifiés.","run.launch.title":"LAUNCH","run.launch.body":"Déploiement en production, transfert du domaine et checklist finale de mise en ligne.","run.pit.title":"PIT CREW","run.pit.body":"Suivi optionnel après lancement pour modifications, ajouts, monitoring et améliorations.","dyno.complexity":"COMPLEXITÉ DU BUILD","dyno.reach":"PORTÉE MARCHÉ","dyno.load":"CHARGE SYSTÈME",
    "services.kicker":"SERVICES / BUILDS","services.title":"Choisissez la base. Puis configurons-la pour votre activité.","services.quickstart":"Site compact, landing page ou lancement ciblé pour petite entreprise.","services.full":"Site professionnel sur mesure construit autour de votre offre, de votre audience et de vos processus.","services.cross":"Architecture multilingue, localisation et adaptation aux marchés internationaux.","services.rebuild":"Refonte, sauvetage et optimisation de sites qui ne servent plus correctement l'activité.","services.shop":"E-commerce pensé pour les produits, la confiance, un checkout clair et la croissance future.","services.fullspec":"Projets complexes sur mesure, intégrations, automatisation et fonctionnalités avancées.","services.pit":"Maintenance mensuelle, suivi, mises à jour, améliorations et support.",
    "setup.kicker":"BUILD YOUR SETUP","setup.title":"Configurez un périmètre de départ réaliste.","setup.estimate":"ESTIMATION DU PROJET","setup.note":"Estimation de planification — pas un tarif fixe. Le périmètre et le devis commercial final suivent une analyse réelle du projet.","setup.cta":"DEMANDER LE DEVIS FINAL",
    "garage.title":"Quatre entreprises. Quatre builds complètement différents.","garage.statement":"Même studio. Logique métier, langage visuel et parcours client différents.",
    "multi.kicker":"PARLEZ À TOUTE LA GRILLE.","multi.title":"Votre activité, comprise partout.","multi.core":"Nous pouvons prendre en charge directement le site et les textes commerciaux en anglais, roumain et français.","multi.expansion":"Nous pouvons construire l'architecture multilingue pour l'allemand, l'italien et le russe, avec validation humaine/native QA des textes commerciaux avant publication.","multi.body":"Nous construisons l'architecture pour la navigation traduite, les métadonnées, l'adaptation du copy, l'UX propre à chaque langue et la localisation — pas seulement un menu de langues.","multi.qa":"La livraison linguistique est définie pour chaque projet afin que chaque marché bénéficie d'une expérience pensée pour lui, et non d'une simple copie traduite automatiquement.",
    "rescue.title":"VOTRE SITE PERD DE LA PUISSANCE.","rescue.body":"Obtenez un diagnostic gratuit de 5 minutes sur le mobile, le design, le copy, la conversion, la performance, la préparation multilingue et les bases de l'accessibilité.","rescue.cta":"DEMANDER UN DEVIS DE REFONTE","rebuildDemo.title":"FAITES-LE PASSER DE PERDU À PRÊT À LANCER.","rebuildDemo.beforeHeadline":"TOUT SE BAT POUR L'ATTENTION.","rebuildDemo.beforeBody":"Hiérarchie faible · CTA enterré · sections génériques · aucun parcours clair.","rebuildDemo.afterHeadline":"UN OBJECTIF. UN PARCOURS CLAIR.","rebuildDemo.afterBody":"Direction distincte · hiérarchie forte · conversion intentionnelle · structure mobile-first.","rebuildDemo.range":"INTENSITÉ DE REFONTE",
    "pit.body":"Un site n'est pas une affiche figée. Nous le gardons à jour, surveillé et utile après le lancement.","included.kicker":"CE QUE VOUS OBTENEZ VRAIMENT","included.title":"Pas seulement des pages. Un système digital fonctionnel.","included.responsive":"Conçu pour fonctionner sur téléphones modernes, tablettes et écrans desktop.","included.performance":"Architecture légère, assets optimisés et motion maîtrisé dès le départ.","included.seo":"Métadonnées, crawlabilité et structure de page préparées pour la recherche.","included.accessibility":"Clavier, sémantique, contraste et reduced-motion pris en compte dans la construction.","included.conversion":"Parcours clairs vers le contact, la réservation, l'achat, la demande ou l'action commerciale suivante.","included.deployment":"Mise en ligne production-ready avec configuration d'hébergement/déploiement adaptée au projet.","included.analytics":"Préparation des points de mesure pour comprendre ce que les utilisateurs font réellement.","included.expansion":"Structure conçue pour que les futures pages, marchés et fonctionnalités n'exigent pas de tout recommencer.","impact.kicker":"IMPACT BUSINESS / OBJECTIFS DE DESIGN","impact.title":"Conçu pour faire avancer l'activité, pas seulement décorer un onglet.","impact.disclaimer":"Ce sont des objectifs de design et de produit — pas des résultats commerciaux garantis. Les résultats dépendent de l'offre, du trafic, du marché, des opérations et du périmètre final.","impact.clarity.title":"CLARTÉ","impact.clarity.body":"Rendre l'offre, le public et la prochaine étape compréhensibles rapidement.","impact.enquiries.title":"DEMANDES","impact.enquiries.body":"Réduire la friction entre l'intérêt et une prise de contact ou demande de devis utile.","impact.action.title":"ACTION","impact.action.body":"Soutenir l'action business qui compte : réserver, acheter, postuler, s'inscrire ou demander.","impact.trust.title":"CONFIANCE","impact.trust.body":"Utiliser structure, copy et cohérence visuelle pour rendre l'activité plus crédible.","impact.reach.title":"PORTÉE","impact.reach.body":"Préparer l'expérience pour plusieurs langues et marchés sans dupliquer le chaos.","impact.growth.title":"CROISSANCE","impact.growth.body":"Construire un système capable d'accueillir plus tard de nouvelles pages, produits, marchés et fonctionnalités.",
    "contact.title":"PRÊT À LANCER ?","contact.body":"Dites-nous ce dont l'activité a besoin. Nous le transformons en périmètre clair de projet.","contact.consent":"J'accepte d'être contacté(e) au sujet de ce projet. Aucun spam.","contact.cta":"TOURNER LA CLÉ","faq.kicker":"AVANT DE TOURNER LA CLÉ","faq.title":"Les questions à poser avant de démarrer un build.","faq.timeline.q":"Combien de temps faut-il pour créer un site ?","faq.timeline.a":"Cela dépend du périmètre. Un projet ciblé peut avancer rapidement ; les projets multilingues, e-commerce ou riches en intégrations demandent plus de temps. Le calendrier final est défini après l'analyse du scope.","faq.ownership.q":"Est-ce que je possède le site ?","faq.ownership.a":"La propriété et la remise sont définies dans la proposition finale. L'objectif est un setup clair et documenté, pas de verrouiller le client dans une infrastructure opaque.","faq.hosting.q":"Pouvez-vous gérer l'hébergement et le domaine ?","faq.hosting.a":"Nous pouvons configurer ou accompagner l'hébergement, le déploiement et le domaine adaptés au projet. Les frais des services tiers restent séparés sauf inclusion explicite.","faq.copy.q":"Pouvez-vous écrire ou réécrire les textes ?","faq.copy.a":"Oui. Copywriting, restructuration et localisation peuvent faire partie du build. Le périmètre linguistique final est défini avant le démarrage.","faq.languages.q":"Dans quelles langues pouvez-vous construire des sites ?","faq.languages.a":"L'anglais, le roumain et le français peuvent être pris en charge directement. L'allemand, l'italien et le russe peuvent être pris en charge via une architecture multilingue et une localisation avec validation humaine/native QA avant publication.","faq.revisions.q":"Comment fonctionnent les révisions ?","faq.revisions.a":"Les cycles de révision et les points de décision sont définis dans la proposition afin que le feedback reste utile et que le projet ne dérive pas indéfiniment.","faq.shop.q":"Pouvez-vous construire e-commerce, réservation ou intégrations ?","faq.shop.a":"Oui. Ces éléments sont scoppés séparément car la complexité varie fortement selon les paiements, le catalogue, les fournisseurs, les API et les besoins opérationnels.","faq.care.q":"Que se passe-t-il après le lancement ?","faq.care.a":"Vous pouvez garder le site de manière autonome ou utiliser PIT CREW pour les changements, ajouts, monitoring et support."
  }
};


copy.de = {
  ...copy.en,
  "nav.home":"Start","nav.services":"Builds","nav.run":"Ablauf","nav.setup":"Setup konfigurieren","nav.garage":"Die Garage","nav.cross":"International","nav.rescue":"Rebuild","nav.pit":"Pit Crew","nav.contact":"Kontakt",
  "hero.tagline":"DEIN BUSINESS. VOLLGAS.","hero.sub":"Websites · E-Commerce · Mehrsprachig · Digitale Systeme","hero.start":"BUILD STARTEN","hero.garage":"IN DIE GARAGE","langs.interfaceLabel":"LAUNCH CTRL ANZEIGEN AUF","langs.buildLabel":"WIR BAUEN KUNDENWEBSITES AUF","langs.expand":"Alle sechs Sprachen sind für Kundenprojekte verfügbar. Finale kommerzielle Texte erhalten bei Bedarf vor Veröffentlichung menschliche/native QA.",
  "manifesto":"Unterschiedliche Unternehmen sollten nicht aussehen, als kämen sie aus derselben Vorlage.","manifestoStrong":"WIR VERKAUFEN KEINE TEMPLATES. WIR BAUEN FÜR DAS BUSINESS.",
  "run.kicker":"THE RUN / ABLAUF","run.title":"Vom ersten Briefing bis zum Live-System.","run.brief.title":"BRIEFING","run.brief.body":"Wir klären Business, Zielgruppe, Ziele, Grenzen und Must-haves.","run.direction.title":"RICHTUNG","run.direction.body":"Wir definieren Struktur, visuelle Sprache, Content-Logik und Conversion-Pfad.","run.build.title":"BUILD","run.build.body":"Wir bauen das echte responsive Produkt — kein statisches Mock-up, das nur wie eine Website aussieht.","run.test.title":"TEST","run.test.body":"Mobile, Inhalte, Formulare, Navigation, Accessibility-Grundlagen und Produktionsverhalten werden geprüft.","run.launch.title":"LAUNCH","run.launch.body":"Produktiv-Deployment, Domain-Übergabe und finale Release-Checkliste.","run.pit.title":"PIT CREW","run.pit.body":"Optional laufende Betreuung für Änderungen, Ergänzungen, Monitoring und Verbesserungen.",
  "dyno.complexity":"BUILD-KOMPLEXITÄT","dyno.reach":"MARKTREICHWEITE","dyno.load":"SYSTEMLAST",
  "services.kicker":"SERVICES / BUILDS","services.title":"Wähle die Maschine. Dann konfigurieren wir sie für dein Business.","services.quickstart":"Kompakte Website, Landingpage oder fokussierter Launch für kleine Unternehmen.","services.full":"Individuelle Business-Website rund um Angebot, Zielgruppe und Workflow.","services.cross":"Mehrsprachige Architektur, Lokalisierung und marktreife Anpassung.","services.rebuild":"Rettung, Redesign und Performance-Bereinigung für Websites, die nicht mehr für das Business arbeiten.","services.shop":"E-Commerce rund um Produkte, Vertrauen, klaren Checkout und zukünftiges Wachstum.","services.fullspec":"Komplexe individuelle Builds, Integrationen, Automatisierung und erweiterte Funktionen.","services.pit":"Monatliche Website-Betreuung, Monitoring, Updates, Verbesserungen und Support.",
  "setup.kicker":"BUILD YOUR SETUP","setup.title":"Konfiguriere eine realistische Start-Spezifikation.","setup.estimate":"GESCHÄTZTER BUILD","setup.note":"Planungsschätzung — kein Festpreis. Der endgültige Umfang und das Angebot folgen nach echter Projektprüfung.","setup.cta":"FINALES ANGEBOT ANFRAGEN",
  "garage.title":"Vier Unternehmen. Vier völlig unterschiedliche Builds.","garage.statement":"Dasselbe Studio. Andere Business-Logik, andere visuelle Sprache, andere Customer Journey.",
  "multi.kicker":"SPRICH MIT DEM GANZEN GRID.","multi.title":"Dein Business, überall verstanden.","multi.core":"Wir bauen und lokalisieren Websites auf Englisch, Rumänisch, Französisch, Deutsch, Italienisch und Russisch.","multi.expansion":"Finale kommerzielle Texte werden bei Bedarf vor Veröffentlichung menschlich geprüft. Native/human QA ist Qualitätskontrolle, keine Sprachbeschränkung.","multi.body":"Wir bauen übersetzte Navigation, Metadaten, Copy-Adaption, sprachspezifische UX und Lokalisierung — nicht nur ein Sprachmenü.","multi.qa":"Der Sprachumfang wird pro Projekt festgelegt, damit jeder Markt eine bewusst gestaltete Erfahrung erhält.",
  "rescue.title":"DEINE WEBSITE VERLIERT LEISTUNG.","rescue.body":"Kostenlose 5-Minuten-Diagnose für Mobile, Design, Copy, Conversion, Performance, Mehrsprachigkeit und Accessibility-Grundlagen.","rescue.cta":"REBUILD-ANGEBOT HOLEN","rebuildDemo.title":"ZIEH SIE VON VERLOREN ZU LAUNCH-READY.","rebuildDemo.beforeHeadline":"ALLES KONKURRIERT.","rebuildDemo.beforeBody":"Schwache Hierarchie · versteckte CTA · generische Sektionen · kein klarer Weg.","rebuildDemo.afterHeadline":"EIN ZIEL. KLARER WEG.","rebuildDemo.afterBody":"Eigene Richtung · starke Hierarchie · gezielte Conversion · mobile-first Struktur.","rebuildDemo.range":"REBUILD-INTENSITÄT",
  "pit.body":"Eine Website ist kein einmaliges Poster. Wir halten sie nach dem Launch aktuell, überwacht und nützlich.",
  "included.kicker":"WAS DU WIRKLICH BEKOMMST","included.title":"Nicht nur Seiten. Ein funktionierendes digitales System.","included.responsive":"Für moderne Smartphones, Tablets und Desktop-Screens gebaut.","included.performance":"Schlanke Architektur, optimierte Assets und sinnvolle Motion von Anfang an.","included.seo":"Metadaten, Crawlability und Seitenstruktur für Suche vorbereitet.","included.accessibility":"Tastatur, Semantik, Kontrast und Reduced Motion werden berücksichtigt.","included.conversion":"Klare Wege zu Kontakt, Buchung, Kauf, Anfrage oder der nächsten Business-Aktion.","included.deployment":"Produktionsreifer Release mit passendem Hosting-/Deployment-Setup.","included.analytics":"Messpunkte können vorbereitet werden, damit die Website zeigt, was Nutzer tatsächlich tun.","included.expansion":"So strukturiert, dass neue Seiten, Märkte und Funktionen später ergänzt werden können.",
  "impact.kicker":"BUSINESS IMPACT / DESIGNZIELE","impact.title":"Gebaut, um das Business zu bewegen — nicht nur einen Browser-Tab zu dekorieren.","impact.disclaimer":"Das sind Design- und Produktziele, keine garantierten Geschäftsergebnisse. Resultate hängen von Angebot, Traffic, Markt, Betrieb und Umfang ab.","impact.clarity.title":"KLARHEIT","impact.clarity.body":"Angebot, Zielgruppe und nächsten Schritt schnell verständlich machen.","impact.enquiries.title":"ANFRAGEN","impact.enquiries.body":"Reibung zwischen Interesse und sinnvoller Kontakt- oder Angebotsanfrage reduzieren.","impact.action.title":"AKTION","impact.action.body":"Die relevante Business-Aktion unterstützen: buchen, kaufen, bewerben, registrieren oder anfragen.","impact.trust.title":"VERTRAUEN","impact.trust.body":"Mit Struktur, Copy und visueller Konsistenz Vertrauen erleichtern.","impact.reach.title":"REICHWEITE","impact.reach.body":"Erfahrung für mehrere Sprachen und Märkte vorbereiten, ohne Chaos zu duplizieren.","impact.growth.title":"WACHSTUM","impact.growth.body":"Ein System bauen, das später neue Seiten, Produkte, Märkte und Funktionen aufnehmen kann.",
  "contact.title":"BEREIT ZUM LAUNCH?","contact.body":"Sag uns, was dein Business braucht. Wir machen daraus einen klaren Build-Umfang.","contact.consent":"Ich stimme zu, wegen dieses Projekts kontaktiert zu werden. Kein Spam.","contact.cta":"SCHLÜSSEL DREHEN",
  "faq.kicker":"BEVOR DU DEN SCHLÜSSEL DREHST","faq.title":"Die Fragen, die vor einem Build wirklich zählen.","faq.timeline.q":"Wie lange dauert eine Website?","faq.timeline.a":"Das hängt vom Umfang ab. Ein fokussierter Build kann schnell gehen; mehrsprachige, E-Commerce- oder integrationslastige Projekte brauchen mehr Zeit. Der finale Zeitplan wird nach Scope-Review vereinbart.","faq.ownership.q":"Gehört mir die Website?","faq.ownership.a":"Eigentum und Übergabe werden im finalen Angebot definiert. Ziel ist ein klares, dokumentiertes Setup — keine mysteriöse Abhängigkeit.","faq.hosting.q":"Könnt ihr Hosting und Domains übernehmen?","faq.hosting.a":"Wir können Hosting, Deployment und Domain-Konfiguration passend zum Projekt einrichten oder begleiten. Drittanbieter-Kosten bleiben separat, sofern nicht ausdrücklich enthalten.","faq.copy.q":"Könnt ihr Copy schreiben oder überarbeiten?","faq.copy.a":"Ja. Copywriting, Restrukturierung und Lokalisierung können Teil des Builds sein. Der finale Sprachumfang wird vor Projektstart vereinbart.","faq.languages.q":"In welchen Sprachen könnt ihr bauen?","faq.languages.a":"Englisch, Rumänisch, Französisch, Deutsch, Italienisch und Russisch sind alle für Kundenprojekte verfügbar. Finale kommerzielle Texte erhalten bei Bedarf menschliche/native QA vor Veröffentlichung.","faq.revisions.q":"Wie funktionieren Revisionen?","faq.revisions.a":"Revisionsrunden und Entscheidungspunkte werden im Angebot definiert, damit Feedback nützlich bleibt und das Projekt nicht endlos driftet.","faq.shop.q":"Könnt ihr E-Commerce, Buchungen oder Integrationen bauen?","faq.shop.a":"Ja. Sie werden separat gescoped, weil die Komplexität je nach Zahlungen, Katalog, Anbieter, APIs und Betrieb stark variiert.","faq.care.q":"Was passiert nach dem Launch?","faq.care.a":"Du kannst die Website unabhängig weiterführen oder PIT CREW für Änderungen, Ergänzungen, Monitoring und Support nutzen."
};
copy.it = {
  ...copy.en,
  "nav.home":"Home","nav.services":"Builds","nav.run":"Processo","nav.setup":"Configura","nav.garage":"Il Garage","nav.cross":"Internazionale","nav.rescue":"Rebuild","nav.pit":"Pit Crew","nav.contact":"Contatti",
  "hero.tagline":"IL TUO BUSINESS. A TUTTO GAS.","hero.sub":"Siti web · E-commerce · Multilingua · Sistemi digitali","hero.start":"AVVIA IL BUILD","hero.garage":"ENTRA NEL GARAGE","langs.interfaceLabel":"VEDI LAUNCH CTRL IN","langs.buildLabel":"REALIZZIAMO SITI CLIENTE IN","langs.expand":"Tutte e sei le lingue sono disponibili per i progetti dei clienti. Il copy commerciale finale riceve QA umana/native quando necessario prima della pubblicazione.",
  "manifesto":"Business diversi non dovrebbero sembrare usciti dallo stesso template.","manifestoStrong":"NON VENDIAMO TEMPLATE. COSTRUIAMO PER IL BUSINESS.",
  "run.kicker":"THE RUN / PROCESSO","run.title":"Dal primo brief al sistema live.","run.brief.title":"BRIEF","run.brief.body":"Chiariamo business, pubblico, obiettivi, vincoli e requisiti essenziali.","run.direction.title":"DIREZIONE","run.direction.body":"Definiamo struttura, linguaggio visivo, logica dei contenuti e percorso di conversione.","run.build.title":"BUILD","run.build.body":"Costruiamo il prodotto responsive reale — non un mockup statico che finge di essere un sito.","run.test.title":"TEST","run.test.body":"Controlliamo mobile, contenuti, form, navigazione, basi di accessibilità e comportamento in produzione.","run.launch.title":"LAUNCH","run.launch.body":"Deployment in produzione, passaggio del dominio e checklist finale di rilascio.","run.pit.title":"PIT CREW","run.pit.body":"Assistenza continuativa opzionale per modifiche, aggiunte, monitoraggio e miglioramenti.",
  "dyno.complexity":"COMPLESSITÀ BUILD","dyno.reach":"COPERTURA MERCATO","dyno.load":"CARICO SISTEMA",
  "services.kicker":"SERVIZI / BUILDS","services.title":"Scegli la macchina. Poi la configuriamo per il tuo business.","services.quickstart":"Sito compatto, landing page o lancio focalizzato per piccole imprese.","services.full":"Sito business personalizzato costruito intorno a offerta, pubblico e workflow.","services.cross":"Architettura multilingue, localizzazione e adattamento pronto per il mercato.","services.rebuild":"Recupero, redesign e pulizia performance per siti che hanno smesso di lavorare per il business.","services.shop":"E-commerce costruito attorno a prodotti, fiducia, checkout chiaro e crescita futura.","services.fullspec":"Build complessi, integrazioni, automazione e funzionalità avanzate.","services.pit":"Cura mensile del sito, monitoraggio, aggiornamenti, miglioramenti e supporto.",
  "setup.kicker":"BUILD YOUR SETUP","setup.title":"Configura una specifica iniziale realistica.","setup.estimate":"BUILD STIMATO","setup.note":"Stima di pianificazione — non tariffa fissa. Scope e preventivo finale seguono una vera revisione del progetto.","setup.cta":"RICHIEDI PREVENTIVO FINALE",
  "garage.title":"Quattro business. Quattro build completamente diversi.","garage.statement":"Stesso studio. Logica di business, linguaggio visivo e customer journey differenti.",
  "multi.kicker":"PARLA A TUTTA LA GRIGLIA.","multi.title":"Il tuo business, capito ovunque.","multi.core":"Realizziamo e localizziamo siti in inglese, rumeno, francese, tedesco, italiano e russo.","multi.expansion":"Il copy commerciale finale viene revisionato da persone madrelingua quando necessario prima della pubblicazione. La QA è controllo qualità, non un limite linguistico.","multi.body":"Costruiamo navigazione tradotta, metadata, adattamento del copy, UX specifica per lingua e localizzazione — non solo un menu lingua.","multi.qa":"La consegna linguistica viene definita per progetto, così ogni mercato riceve un’esperienza intenzionale.",
  "rescue.title":"IL TUO SITO STA PERDENDO POTENZA.","rescue.body":"Diagnosi gratuita di 5 minuti su mobile, design, copy, conversione, performance, multilingua e basi di accessibilità.","rescue.cta":"RICHIEDI PREVENTIVO REBUILD","rebuildDemo.title":"TRASCINALO DA PERSO A PRONTO AL LANCIO.","rebuildDemo.beforeHeadline":"TUTTO COMPETE.","rebuildDemo.beforeBody":"Gerarchia debole · CTA nascosta · sezioni generiche · nessun percorso chiaro.","rebuildDemo.afterHeadline":"UN OBIETTIVO. PERCORSO CHIARO.","rebuildDemo.afterBody":"Direzione distinta · gerarchia forte · conversione intenzionale · struttura mobile-first.","rebuildDemo.range":"INTENSITÀ REBUILD",
  "pit.body":"Un sito non è un poster una tantum. Lo teniamo aggiornato, monitorato e utile dopo il lancio.",
  "included.kicker":"COSA RICEVI DAVVERO","included.title":"Non solo pagine. Un sistema digitale funzionante.","included.responsive":"Progettato per funzionare su smartphone moderni, tablet e desktop.","included.performance":"Architettura snella, asset ottimizzati e motion sensato fin dall’inizio.","included.seo":"Metadata, crawlability e struttura pagina preparati per la ricerca.","included.accessibility":"Tastiera, semantica, contrasto e reduced motion considerati nel build.","included.conversion":"Percorsi chiari verso contatto, prenotazione, acquisto, richiesta o prossima azione commerciale.","included.deployment":"Release pronta per produzione con hosting/deployment adeguato al progetto.","included.analytics":"Possiamo predisporre misurazione per capire cosa fanno davvero gli utenti.","included.expansion":"Strutturato per aggiungere in futuro pagine, mercati e funzioni senza ripartire da zero.",
  "impact.kicker":"IMPATTO BUSINESS / OBIETTIVI DESIGN","impact.title":"Costruito per muovere il business, non per decorare una scheda browser.","impact.disclaimer":"Sono obiettivi di design e prodotto, non risultati commerciali garantiti. I risultati dipendono da offerta, traffico, mercato, operazioni e scope.","impact.clarity.title":"CHIAREZZA","impact.clarity.body":"Rendere offerta, pubblico e prossimo passo comprensibili rapidamente.","impact.enquiries.title":"RICHIESTE","impact.enquiries.body":"Ridurre l’attrito tra interesse e una richiesta di contatto o preventivo utile.","impact.action.title":"AZIONE","impact.action.body":"Supportare l’azione che conta: prenotare, comprare, candidarsi, registrarsi o chiedere informazioni.","impact.trust.title":"FIDUCIA","impact.trust.body":"Usare struttura, copy e coerenza visiva per rendere il business più affidabile.","impact.reach.title":"PORTATA","impact.reach.body":"Preparare l’esperienza per più lingue e mercati senza duplicare il caos.","impact.growth.title":"CRESCITA","impact.growth.body":"Costruire un sistema pronto per nuove pagine, prodotti, mercati e funzionalità.",
  "contact.title":"PRONTO AL LANCIO?","contact.body":"Dicci cosa serve al business. Lo trasformiamo in uno scope chiaro.","contact.consent":"Accetto di essere contattato per questo progetto. Niente spam.","contact.cta":"GIRA LA CHIAVE",
  "faq.kicker":"PRIMA DI GIRARE LA CHIAVE","faq.title":"Le domande che vale la pena fare prima di iniziare un build.","faq.timeline.q":"Quanto tempo richiede un sito?","faq.timeline.a":"Dipende dallo scope. Un build focalizzato può procedere rapidamente; multilingua, e-commerce e integrazioni richiedono più tempo. La timeline finale viene concordata dopo la revisione dello scope.","faq.ownership.q":"Il sito è mio?","faq.ownership.a":"Proprietà e handoff sono definiti nella proposta finale. L’obiettivo è un setup chiaro e documentato, non bloccare il cliente in infrastrutture misteriose.","faq.hosting.q":"Potete gestire hosting e domini?","faq.hosting.a":"Possiamo configurare o guidare hosting, deployment e dominio in modo appropriato al progetto. I costi di terze parti restano separati salvo inclusione esplicita.","faq.copy.q":"Potete scrivere o riscrivere il copy?","faq.copy.a":"Sì. Copywriting, ristrutturazione e localizzazione possono far parte del build. Lo scope linguistico finale viene concordato prima dell’avvio.","faq.languages.q":"In quali lingue potete costruire?","faq.languages.a":"Inglese, rumeno, francese, tedesco, italiano e russo sono tutti disponibili per i progetti cliente. Il copy commerciale finale riceve QA umana/native quando necessario prima della pubblicazione.","faq.revisions.q":"Come funzionano le revisioni?","faq.revisions.a":"Round di revisione e punti decisionali vengono definiti nella proposta per mantenere il feedback utile e impedire derive infinite.","faq.shop.q":"Potete costruire e-commerce, booking o integrazioni?","faq.shop.a":"Sì. Vengono scoperte separatamente perché la complessità varia molto in base a pagamenti, catalogo, provider, API e requisiti operativi.","faq.care.q":"Cosa succede dopo il lancio?","faq.care.a":"Puoi tenere il sito in autonomia oppure usare PIT CREW per modifiche, aggiunte, monitoraggio e supporto."
};
copy.ru = {
  ...copy.en,
  "nav.home":"Главная","nav.services":"Сборки","nav.run":"Процесс","nav.setup":"Конфигуратор","nav.garage":"Гараж","nav.cross":"Международно","nav.rescue":"Rebuild","nav.pit":"Pit Crew","nav.contact":"Контакты",
  "hero.tagline":"ВАШ БИЗНЕС. ПОЛНЫЙ ГАЗ.","hero.sub":"Сайты · E-commerce · Мультиязычность · Цифровые системы","hero.start":"НАЧАТЬ BUILD","hero.garage":"ВОЙТИ В ГАРАЖ","langs.interfaceLabel":"СМОТРЕТЬ LAUNCH CTRL НА","langs.buildLabel":"МЫ СОЗДАЁМ САЙТЫ КЛИЕНТОВ НА","langs.expand":"Все шесть языков доступны для клиентских проектов. Финальный коммерческий текст при необходимости проходит человеческую/native QA перед публикацией.",
  "manifesto":"Разные бизнесы не должны выглядеть так, будто сделаны по одному шаблону.","manifestoStrong":"МЫ НЕ ПРОДАЁМ ШАБЛОНЫ. МЫ СТРОИМ ПОД БИЗНЕС.",
  "run.kicker":"THE RUN / ПРОЦЕСС","run.title":"От первого брифа до live-системы.","run.brief.title":"БРИФ","run.brief.body":"Уточняем бизнес, аудиторию, цели, ограничения и обязательные требования.","run.direction.title":"НАПРАВЛЕНИЕ","run.direction.body":"Определяем структуру, визуальный язык, логику контента и путь конверсии.","run.build.title":"BUILD","run.build.body":"Создаём реальный responsive-продукт — не статичный макет, притворяющийся сайтом.","run.test.title":"ТЕСТ","run.test.body":"Проверяем мобильную версию, контент, формы, навигацию, основы accessibility и production-поведение.","run.launch.title":"LAUNCH","run.launch.body":"Production deployment, передача домена и финальный release-чеклист.","run.pit.title":"PIT CREW","run.pit.body":"Опциональная поддержка после запуска: изменения, дополнения, мониторинг и улучшения.",
  "dyno.complexity":"СЛОЖНОСТЬ BUILD","dyno.reach":"ОХВАТ РЫНКА","dyno.load":"НАГРУЗКА СИСТЕМЫ",
  "services.kicker":"УСЛУГИ / BUILDS","services.title":"Выберите машину. Затем настроим её под ваш бизнес.","services.quickstart":"Компактный сайт, landing page или сфокусированный запуск малого бизнеса.","services.full":"Индивидуальный бизнес-сайт под ваше предложение, аудиторию и workflow.","services.cross":"Мультиязычная архитектура, локализация и адаптация под рынок.","services.rebuild":"Спасение, редизайн и очистка performance для сайтов, которые перестали работать на бизнес.","services.shop":"E-commerce вокруг продуктов, доверия, понятного checkout и будущего роста.","services.fullspec":"Сложные кастомные builds, интеграции, автоматизация и расширенный функционал.","services.pit":"Ежемесячное обслуживание, мониторинг, обновления, улучшения и поддержка.",
  "setup.kicker":"BUILD YOUR SETUP","setup.title":"Соберите реалистичную стартовую спецификацию.","setup.estimate":"ОЦЕНКА BUILD","setup.note":"Плановая оценка — не фиксированный тариф. Финальный scope и коммерческое предложение формируются после реального разбора проекта.","setup.cta":"ЗАПРОСИТЬ ФИНАЛЬНУЮ СМЕТУ",
  "garage.title":"Четыре бизнеса. Четыре совершенно разные сборки.","garage.statement":"Одна студия. Разная бизнес-логика, визуальный язык и путь клиента.",
  "multi.kicker":"ГОВОРИТЕ СО ВСЕЙ СЕТКОЙ.","multi.title":"Ваш бизнес понятен везде.","multi.core":"Мы создаём и локализуем сайты на английском, румынском, французском, немецком, итальянском и русском.","multi.expansion":"Финальный коммерческий текст при необходимости проверяется человеком/native reviewer перед публикацией. QA — это контроль качества, а не языковое ограничение.","multi.body":"Мы строим переведённую навигацию, metadata, адаптацию copy, языковой UX и локализацию — а не просто переключатель языка.","multi.qa":"Языковой объём определяется для каждого проекта, чтобы каждый рынок получил продуманный опыт.",
  "rescue.title":"ВАШ САЙТ ТЕРЯЕТ МОЩНОСТЬ.","rescue.body":"Бесплатная 5-минутная диагностика mobile, design, copy, conversion, performance, мультиязычной готовности и основ accessibility.","rescue.cta":"ПОЛУЧИТЬ REBUILD-СМЕТУ","rebuildDemo.title":"ПЕРЕТАЩИТЕ ЕГО ИЗ «ПОТЕРЯН» В «ГОТОВ К ЗАПУСКУ».","rebuildDemo.beforeHeadline":"ВСЁ КОНКУРИРУЕТ.","rebuildDemo.beforeBody":"Слабая иерархия · спрятанный CTA · типовые секции · нет ясного пути.","rebuildDemo.afterHeadline":"ОДНА ЦЕЛЬ. ЯСНЫЙ ПУТЬ.","rebuildDemo.afterBody":"Своя визуальная линия · сильная иерархия · осознанная conversion · mobile-first структура.","rebuildDemo.range":"ИНТЕНСИВНОСТЬ REBUILD",
  "pit.body":"Сайт — не одноразовый плакат. После запуска мы поддерживаем его актуальным, контролируемым и полезным.",
  "included.kicker":"ЧТО ВЫ РЕАЛЬНО ПОЛУЧАЕТЕ","included.title":"Не просто страницы. Рабочая цифровая система.","included.responsive":"Создано для современных телефонов, планшетов и desktop-экранов.","included.performance":"Лёгкая архитектура, оптимизированные assets и разумная анимация с самого начала.","included.seo":"Metadata, crawlability и структура страниц подготовлены для поиска.","included.accessibility":"Keyboard, semantics, contrast и reduced-motion учитываются в build.","included.conversion":"Ясные пути к контакту, бронированию, покупке, запросу или следующему бизнес-действию.","included.deployment":"Production-ready релиз с подходящим hosting/deployment setup.","included.analytics":"Можно подготовить измерения, чтобы сайт показывал, что пользователи реально делают.","included.expansion":"Структура позволяет позже добавлять страницы, рынки и функции без старта с нуля.",
  "impact.kicker":"БИЗНЕС-ЭФФЕКТ / DESIGN TARGETS","impact.title":"Создано, чтобы двигать бизнес, а не украшать вкладку браузера.","impact.disclaimer":"Это цели дизайна и продукта, а не гарантированные коммерческие результаты. Итог зависит от предложения, трафика, рынка, операций и scope.","impact.clarity.title":"ЯСНОСТЬ","impact.clarity.body":"Быстро сделать понятными предложение, аудиторию и следующий шаг.","impact.enquiries.title":"ЗАПРОСЫ","impact.enquiries.body":"Уменьшить трение между интересом и полезным контактом или запросом цены.","impact.action.title":"ДЕЙСТВИЕ","impact.action.body":"Поддержать главное бизнес-действие: забронировать, купить, подать заявку, зарегистрироваться или связаться.","impact.trust.title":"ДОВЕРИЕ","impact.trust.body":"Структурой, copy и визуальной последовательностью сделать бизнес легче для доверия.","impact.reach.title":"ОХВАТ","impact.reach.body":"Подготовить опыт для нескольких языков и рынков без дублирования хаоса.","impact.growth.title":"РОСТ","impact.growth.body":"Построить систему, которая позже примет новые страницы, продукты, рынки и функции.",
  "contact.title":"ГОТОВЫ К ЗАПУСКУ?","contact.body":"Расскажите, что нужно бизнесу. Мы превратим это в ясный scope.","contact.consent":"Я согласен(-на) на связь по этому проекту. Без спама.","contact.cta":"ПОВЕРНУТЬ КЛЮЧ",
  "faq.kicker":"ПЕРЕД ТЕМ КАК ПОВЕРНУТЬ КЛЮЧ","faq.title":"Вопросы, которые стоит задать до начала build.","faq.timeline.q":"Сколько времени занимает сайт?","faq.timeline.a":"Зависит от scope. Сфокусированный build может двигаться быстро; мультиязычные, e-commerce и интеграционные проекты требуют больше времени. Финальный срок согласуется после review scope.","faq.ownership.q":"Сайт принадлежит мне?","faq.ownership.a":"Право собственности и handoff определяются в финальном предложении. Цель — ясный документированный setup, а не привязка клиента к непонятной инфраструктуре.","faq.hosting.q":"Вы можете заняться hosting и domains?","faq.hosting.a":"Мы можем настроить или сопроводить hosting, deployment и domain configuration под проект. Сторонние расходы остаются отдельно, если явно не включены.","faq.copy.q":"Вы можете написать или переписать copy?","faq.copy.a":"Да. Copywriting, restructuring и localization могут входить в build. Финальный языковой scope согласуется до старта.","faq.languages.q":"На каких языках вы можете создавать сайты?","faq.languages.a":"Английский, румынский, французский, немецкий, итальянский и русский доступны для клиентских проектов. Финальный коммерческий текст при необходимости проходит человеческую/native QA перед публикацией.","faq.revisions.q":"Как работают правки?","faq.revisions.a":"Раунды правок и точки принятия решений определяются в предложении, чтобы feedback оставался полезным, а проект не растягивался бесконечно.","faq.shop.q":"Вы можете сделать e-commerce, booking или integrations?","faq.shop.a":"Да. Они оцениваются отдельно, потому что сложность сильно зависит от платежей, каталога, провайдеров, API и операционных требований.","faq.care.q":"Что происходит после запуска?","faq.care.a":"Можно вести сайт самостоятельно или использовать PIT CREW для изменений, дополнений, мониторинга и поддержки."
};

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

function applyLanguage(lang) {
  const active = copy[lang] ? lang : "en";
  document.documentElement.lang = active;
  $$('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    el.textContent = copy[active]?.[key] || copy.en[key] || el.textContent;
  });
  $$('.lang').forEach(btn => {
    const isActive = btn.dataset.lang === lang;
    btn.classList.toggle('is-active', isActive);
    btn.setAttribute('aria-pressed', String(isActive));
  });
  localStorage.setItem('launchCtrlLang', lang);
}

$$('.lang').forEach(btn => btn.addEventListener('click', () => applyLanguage(btn.dataset.lang)));

const savedLang = localStorage.getItem('launchCtrlLang');
if (savedLang) applyLanguage(savedLang);

const configForm = $('#configForm');
if (configForm) {
  const controls = {
    pages: $('#pages'), langs: $('#langs'), commerce: $('#commerce'), booking: $('#booking'),
    copywriting: $('#copywriting'), localization: $('#localization'), analytics: $('#analytics'),
    seo: $('#seo'), accessibility: $('#accessibility'), integrations: $('#integrations'), maintenance: $('#maintenance')
  };

  const money = (n) => new Intl.NumberFormat('en-US', {style:'currency', currency:'EUR', maximumFractionDigits:0}).format(Math.round(n / 50) * 50);
  const estimate = () => {
    const pages = Number(controls.pages.value);
    const langs = Number(controls.langs.value);
    let low = 620 + pages * 105;
    let high = 880 + pages * 165;
    const add = (on, l, h) => { if (on) { low += l; high += h; } };
    if (langs > 1) { low += (langs - 1) * (240 + pages * 18); high += (langs - 1) * (420 + pages * 30); }
    add(controls.commerce.checked, 850, 1800);
    add(controls.booking.checked, 280, 650);
    add(controls.copywriting.checked, 350, 950);
    add(controls.localization.checked, Math.max(0, langs - 1) * 190, Math.max(0, langs - 1) * 460);
    add(controls.analytics.checked, 80, 180);
    add(controls.seo.checked, 160, 420);
    add(controls.accessibility.checked, 140, 380);
    add(controls.integrations.checked, 420, 1400);
    if (pages > 15) { low += 650; high += 1100; }

    $('#pagesOut').value = pages; $('#langsOut').value = langs;
    $('#specPages').textContent = pages; $('#specLangs').textContent = langs;
    $('#specBooking').textContent = controls.booking.checked ? 'ON' : 'OFF';
    $('#specCommerce').textContent = controls.commerce.checked ? 'ON' : 'OFF';
    $('#specCare').textContent = controls.maintenance.checked ? 'ON' : 'OFF';
    $('#estimateValue').textContent = `${money(low)}–${money(high)}`;

    const featureCount = ['commerce','booking','copywriting','localization','analytics','seo','accessibility','integrations','maintenance']
      .filter(key => controls[key].checked).length;
    const complexity = Math.min(100, Math.round(12 + pages * 1.6 + featureCount * 5 + Math.max(0, langs - 1) * 3));
    const reach = Math.min(100, Math.round(8 + langs * 13 + (controls.localization.checked ? 12 : 0) + (controls.commerce.checked ? 5 : 0)));
    const load = Math.min(100, Math.round(10 + pages * 1.1 + featureCount * 4 + (controls.commerce.checked ? 12 : 0) + (controls.integrations.checked ? 16 : 0)));
    [['complexity',complexity],['reach',reach],['load',load]].forEach(([name,value]) => {
      const out = $('#' + name + 'Out');
      const bar = $('#' + name + 'Bar');
      if (out) out.textContent = value;
      if (bar) bar.style.width = value + '%';
    });
  };
  Object.values(controls).filter(Boolean).forEach(el => el.addEventListener('input', estimate));
  estimate();
}

const diagnosisForm = $('#diagnosisForm');
if (diagnosisForm) {
  diagnosisForm.addEventListener('submit', (e) => {
    e.preventDefault();
    const url = $('#diagnosisUrl')?.value.trim() || '';
    const params = new URLSearchParams({need:'Rebuild'});
    if (url) params.set('website', url);
    window.location.href = './contact.html?' + params.toString();
  });
}

const leadForm = $('#leadForm');
if (leadForm) {
  const params = new URLSearchParams(window.location.search);
  const website = params.get('website');
  const need = params.get('need');
  if (website && leadForm.elements.website) leadForm.elements.website.value = website;
  if (need && leadForm.elements.need) leadForm.elements.need.value = need;

  leadForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const status = $('#leadStatus');
    const button = e.currentTarget.querySelector('button[type="submit"]');
    status.textContent = 'Sending…'; button.disabled = true;
    const data = Object.fromEntries(new FormData(e.currentTarget).entries());
    try {
      const res = await fetch('/api/lead', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(data)});
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || 'Could not send the project brief.');
      status.textContent = 'Build request received. We’ll get back to you with the next step.';
      e.currentTarget.reset();
    } catch (err) {
      status.textContent = err.message || 'Could not send. Please try again.';
    } finally { button.disabled = false; }
  });
}

const rebuildSlider = $('#rebuildSlider');
if (rebuildSlider) {
  const updateRebuild = () => {
    const value = Number(rebuildSlider.value);
    const after = $('#rebuildAfter');
    const divider = $('#rebuildDivider');
    const percent = $('#rebuildPercent');
    if (after) after.style.clipPath = `inset(0 0 0 ${100 - value}%)`;
    if (divider) divider.style.left = value + '%';
    if (percent) percent.textContent = value + '%';
  };
  rebuildSlider.addEventListener('input', updateRebuild);
  updateRebuild();
}

const year = $('#year');
if (year) year.textContent = new Date().getFullYear();
