(() => {
  const T = {
    ro: {
      "Skip to content":"Sari la conținut","HOME":"ACASĂ","BUILDS":"BUILDS","GARAGE":"GARAJ","CROSS-BORDER":"INTERNAȚIONAL","REBUILD":"REBUILD","PIT CREW":"PIT CREW","CONTACT":"CONTACT",
      "LIVE SYSTEM":"SISTEM LIVE","01 — SPEED":"01 — VITEZĂ","02 — CLARITY":"02 — CLARITATE","03 — REACH":"03 — ACOPERIRE","CORE":"NUCLEU","MOTION":"MIȘCARE","MODE":"MOD","STATIC-FIRST":"STATIC-FIRST","OPTIMIZED":"OPTIMIZAT","FULL SEND":"FULL SEND",
      "CHOOSE YOUR ROUTE":"ALEGE TRASEUL","One studio. Separate systems.":"Un studio. Sisteme distincte.","Services, process, configurator and build scope.":"Servicii, proces, configurator și scope de proiect.","Selected studio builds across completely different industries.":"Build-uri selectate din industrii complet diferite.","Languages, localization and international-ready architecture.":"Limbi, localizare și arhitectură pregătită internațional.","Website rescue, diagnosis and redesign.":"Salvare, diagnoză și redesign de website.","Ongoing maintenance, updates and support.":"Mentenanță, actualizări și suport continuu.","Send the brief and turn it into a real scope.":"Trimite brief-ul și îl transformăm într-un scope real.",
      "SELECTED BUILDS":"BUILD-URI SELECTATE","Different business. Different machine.":"Afacere diferită. Mașină diferită.","OPEN THE FULL GARAGE →":"DESCHIDE TOT GARAJUL →","CULTURE / COMMUNITY":"CULTURĂ / COMUNITATE","HEALTHCARE / REHABILITATION":"SĂNĂTATE / RECUPERARE","ASSESSMENT / SAAS":"EVALUARE / SAAS","KNOWLEDGE / EXPLORATION":"CUNOAȘTERE / EXPLORARE",
      "CHOOSE THE MACHINE.":"ALEGE MAȘINA.","FAST / LEAN / CONVERSION-READY":"RAPID / LEAN / GATA DE CONVERSIE","CUSTOM / SCALABLE / DISTINCTIVE":"CUSTOM / SCALABIL / DISTINCTIV","RO / EN / FR / DE / IT / RU":"RO / EN / FR / DE / IT / RU","AUDIT / REDESIGN / RESCUE":"AUDIT / REDESIGN / SALVARE","STORE / PAYMENTS / OPERATIONS":"MAGAZIN / PLĂȚI / OPERAȚIUNI","INTEGRATIONS / SYSTEMS / CUSTOM":"INTEGRĂRI / SISTEME / CUSTOM","RECURRING / CARE / SUPPORT":"RECURENT / ÎNGRIJIRE / SUPORT",
      "PAGES":"PAGINI","LANGUAGES":"LIMBI","E-COMMERCE":"E-COMMERCE","BOOKING":"REZERVĂRI","COPYWRITING":"COPYWRITING","LOCALIZATION":"LOCALIZARE","ANALYTICS":"ANALYTICS","SEO FOUNDATIONS":"BAZE SEO","ACCESSIBILITY":"ACCESIBILITATE","INTEGRATIONS":"INTEGRĂRI","CARE PLAN":"PLAN DE ÎNGRIJIRE","DIGITAL SPEC SHEET":"FIȘĂ TEHNICĂ DIGITALĂ","OFF":"OFF",
      "RESPONSIVE BUILD":"BUILD RESPONSIVE","PERFORMANCE CORE":"NUCLEU DE PERFORMANȚĂ","ACCESSIBILITY BASICS":"BAZE DE ACCESIBILITATE","CONVERSION STRUCTURE":"STRUCTURĂ DE CONVERSIE","DEPLOYMENT":"DEPLOYMENT","ANALYTICS READY":"GATA PENTRU ANALYTICS","EXPANSION PATH":"CALE DE EXTINDERE","Designed to work across modern screens.":"Conceput să funcționeze pe ecrane moderne.","Lean architecture and optimized assets.":"Arhitectură lean și asset-uri optimizate.","Metadata and page structure prepared for search.":"Metadata și structură de pagină pregătite pentru căutare.","Semantics, contrast and reduced-motion considerations.":"Semantică, contrast și reduced-motion integrate.","Clear routes to the next business action.":"Trasee clare către următoarea acțiune comercială.","Production-ready release and setup.":"Release și setup pregătite pentru producție.","Prepared for measurement.":"Pregătit pentru măsurare.","Built so future growth does not require starting over.":"Construit astfel încât creșterea viitoare să nu ceară un restart.",
      "DIFFERENT BUSINESS. DIFFERENT MACHINE.":"AFACERE DIFERITĂ. MAȘINĂ DIFERITĂ.","Selected studio builds and independent ventures. Status is labelled honestly — no fake client results.":"Build-uri selectate și proiecte independente. Statutul este etichetat sincer — fără rezultate false atribuite clienților.","THE POINT ISN'T TO SHOW EIGHT VERSIONS OF THE SAME WEBSITE. IT'S TO SHOW EIGHT DIFFERENT BUSINESS LOGICS.":"SCOPUL NU ESTE SĂ ARĂTĂM OPT VERSIUNI ALE ACELUIAȘI WEBSITE. CI OPT LOGICI DE BUSINESS DIFERITE.",
      "SPEAK TO THE WHOLE GRID.":"VORBEȘTE CU TOATĂ GRILA.","SIX-LANGUAGE STUDIO":"STUDIO ÎN ȘASE LIMBI","QUALITY CONTROL":"CONTROL DE CALITATE","NATIVE / HUMAN QA":"QA NATIV / UMAN","We build and localize websites across all six studio languages.":"Construim și localizăm website-uri în toate cele șase limbi ale studioului.","Final commercial copy is reviewed where required before publication. QA is a quality standard, not a language limitation.":"Copy-ul comercial final este verificat acolo unde este necesar înainte de publicare. QA este un standard de calitate, nu o limitare de limbă.","LANGUAGE ARCHITECTURE":"ARHITECTURĂ LINGVISTICĂ","Routes, menus and content structure designed for more than one language.":"Rute, meniuri și structură de conținut proiectate pentru mai multe limbi.","LOCALIZED UX":"UX LOCALIZAT","Not every market needs the exact same text length, order or CTA language.":"Nu fiecare piață are nevoie de aceeași lungime a textului, aceeași ordine sau același limbaj CTA.","METADATA":"METADATA","Titles, descriptions and search-facing copy prepared per language.":"Titluri, descrieri și copy pentru căutare pregătite pe fiecare limbă.","NATIVE QA":"QA NATIV","Final commercial copy is reviewed where required before publication across the six-language workflow.":"Copy-ul comercial final este verificat unde este necesar în fluxul celor șase limbi.",
      "WEBSITE URL":"URL WEBSITE","BEFORE":"ÎNAINTE","AFTER / LAUNCH CTRL":"DUPĂ / LAUNCH CTRL","MOVE":"MUTĂ",
      "KEEP IT TUNED.":"ȚINE-L REGLAT.","UPDATES":"ACTUALIZĂRI","Content and controlled technical updates.":"Actualizări de conținut și tehnice controlate.","SMALL CHANGES":"MODIFICĂRI MICI","Copy, images, links and minor layout changes.":"Copy, imagini, linkuri și mici modificări de layout.","MONITORING":"MONITORIZARE","Periodic checks appropriate to the project stack.":"Verificări periodice potrivite stack-ului proiectului.","PAGE ADDITIONS":"PAGINI NOI","New pages or sections without a full rebuild.":"Pagini sau secțiuni noi fără rebuild complet.","IMPROVEMENTS":"ÎMBUNĂTĂȚIRI","Incremental UX, conversion and performance refinements.":"Îmbunătățiri incrementale de UX, conversie și performanță.","SUPPORT":"SUPORT","A clear route for ongoing website work after launch.":"O cale clară pentru lucrările continue după lansare.","BUILD IT ONCE. KEEP IMPROVING IT.":"CONSTRUIEȘTE-L O DATĂ. ÎMBUNĂTĂȚEȘTE-L CONTINUU.","ASK ABOUT PIT CREW":"ÎNTREABĂ DESPRE PIT CREW",
      "NAME":"NUME","BUSINESS":"AFACERE","EMAIL":"EMAIL","COUNTRY":"ȚARĂ","INDUSTRY":"INDUSTRIE","EXISTING WEBSITE":"WEBSITE EXISTENT","WHAT DO YOU NEED?":"DE CE AI NEVOIE?","Select":"Selectează","Quickstart":"Quickstart","Full Build":"Full Build","Cross-Border":"Cross-Border","Rebuild":"Rebuild","Shop Build":"Shop Build","Full Spec":"Full Spec","Pit Crew":"Pit Crew","APPROX. PAGES":"PAGINI APROX.","FUNCTIONALITY":"FUNCȚIONALITATE","DEADLINE":"TERMEN","BUDGET RANGE":"BUGET","NOTES":"NOTIȚE","COMPANY WEBSITE":"WEBSITE COMPANIE",
      "FAQ":"FAQ","BACK TO LAUNCH CTRL":"ÎNAPOI LA LAUNCH CTRL","PRIVACY":"CONFIDENȚIALITATE","← BACK TO THE GARAGE":"← ÎNAPOI ÎN GARAJ","CURRENT STATE / ACTIVE BUILD":"STARE CURENTĂ / BUILD ACTIV","IN DEVELOPMENT / STUDIO BUILD":"ÎN DEZVOLTARE / BUILD DE STUDIO","01 / CHALLENGE":"01 / PROVOCARE","02 / DIRECTION":"02 / DIRECȚIE","03 / SYSTEM":"03 / SISTEM","04 / LANGUAGES":"04 / LIMBI","THE BUSINESS FIRST.":"BUSINESS-UL ÎNTÂI.","NO TEMPLATE LOGIC.":"FĂRĂ LOGICĂ DE TEMPLATE.","WHAT THE BUILD NEEDS TO DO.":"CE TREBUIE SĂ FACĂ BUILD-UL.","MARKET READY.":"PREGĂTIT PENTRU PIAȚĂ.","NEXT BUILD":"URMĂTORUL BUILD"
    },
    fr: {
      "Skip to content":"Aller au contenu","HOME":"ACCUEIL","BUILDS":"BUILDS","GARAGE":"GARAGE","CROSS-BORDER":"INTERNATIONAL","REBUILD":"REBUILD","PIT CREW":"PIT CREW","CONTACT":"CONTACT",
      "LIVE SYSTEM":"SYSTÈME LIVE","01 — SPEED":"01 — VITESSE","02 — CLARITY":"02 — CLARTÉ","03 — REACH":"03 — PORTÉE","CHOOSE YOUR ROUTE":"CHOISISSEZ VOTRE ROUTE","One studio. Separate systems.":"Un studio. Des systèmes distincts.","Selected studio builds across completely different industries.":"Sélection de builds dans des secteurs totalement différents.","OPEN THE FULL GARAGE →":"OUVRIR TOUT LE GARAGE →",
      "CHOOSE THE MACHINE.":"CHOISISSEZ LA MACHINE.","PAGES":"PAGES","LANGUAGES":"LANGUES","BOOKING":"RÉSERVATION","LOCALIZATION":"LOCALISATION","ACCESSIBILITY":"ACCESSIBILITÉ","INTEGRATIONS":"INTÉGRATIONS","CARE PLAN":"PLAN DE SUIVI","DIGITAL SPEC SHEET":"FICHE TECHNIQUE DIGITALE",
      "DIFFERENT BUSINESS. DIFFERENT MACHINE.":"BUSINESS DIFFÉRENT. MACHINE DIFFÉRENTE.","Selected studio builds and independent ventures. Status is labelled honestly — no fake client results.":"Builds sélectionnés et projets indépendants. Le statut est indiqué honnêtement — aucun faux résultat client.",
      "SPEAK TO THE WHOLE GRID.":"PARLEZ À TOUTE LA GRILLE.","SIX-LANGUAGE STUDIO":"STUDIO EN SIX LANGUES","QUALITY CONTROL":"CONTRÔLE QUALITÉ","NATIVE / HUMAN QA":"QA NATIVE / HUMAINE","We build and localize websites across all six studio languages.":"Nous concevons et localisons des sites dans les six langues du studio.","Final commercial copy is reviewed where required before publication. QA is a quality standard, not a language limitation.":"Le copy commercial final est relu lorsque nécessaire avant publication. La QA est un standard de qualité, pas une limitation linguistique.",
      "WEBSITE URL":"URL DU SITE","BEFORE":"AVANT","AFTER / LAUNCH CTRL":"APRÈS / LAUNCH CTRL","MOVE":"DÉPLACER","KEEP IT TUNED.":"GARDEZ-LE AFFÛTÉ.","UPDATES":"MISES À JOUR","SMALL CHANGES":"PETITES MODIFICATIONS","MONITORING":"SUIVI","PAGE ADDITIONS":"AJOUTS DE PAGES","IMPROVEMENTS":"AMÉLIORATIONS","SUPPORT":"SUPPORT","BUILD IT ONCE. KEEP IMPROVING IT.":"CONSTRUISEZ-LE UNE FOIS. CONTINUEZ À L’AMÉLIORER.","ASK ABOUT PIT CREW":"DEMANDER PIT CREW",
      "NAME":"NOM","BUSINESS":"ENTREPRISE","COUNTRY":"PAYS","INDUSTRY":"SECTEUR","EXISTING WEBSITE":"SITE EXISTANT","WHAT DO YOU NEED?":"DE QUOI AVEZ-VOUS BESOIN ?","Select":"Sélectionner","APPROX. PAGES":"PAGES APPROX.","FUNCTIONALITY":"FONCTIONNALITÉS","DEADLINE":"DÉLAI","BUDGET RANGE":"BUDGET","NOTES":"NOTES","COMPANY WEBSITE":"SITE DE L’ENTREPRISE",
      "BACK TO LAUNCH CTRL":"RETOUR À LAUNCH CTRL","PRIVACY":"CONFIDENTIALITÉ","← BACK TO THE GARAGE":"← RETOUR AU GARAGE","CURRENT STATE / ACTIVE BUILD":"ÉTAT ACTUEL / BUILD ACTIF","IN DEVELOPMENT / STUDIO BUILD":"EN DÉVELOPPEMENT / BUILD STUDIO","01 / CHALLENGE":"01 / DÉFI","02 / DIRECTION":"02 / DIRECTION","03 / SYSTEM":"03 / SYSTÈME","04 / LANGUAGES":"04 / LANGUES","THE BUSINESS FIRST.":"LE BUSINESS D’ABORD.","NO TEMPLATE LOGIC.":"AUCUNE LOGIQUE DE TEMPLATE.","WHAT THE BUILD NEEDS TO DO.":"CE QUE LE BUILD DOIT FAIRE.","MARKET READY.":"PRÊT POUR LE MARCHÉ.","NEXT BUILD":"BUILD SUIVANT"
    },
    de: {
      "Skip to content":"Zum Inhalt springen","HOME":"START","BUILDS":"BUILDS","GARAGE":"GARAGE","CROSS-BORDER":"INTERNATIONAL","REBUILD":"REBUILD","PIT CREW":"PIT CREW","CONTACT":"KONTAKT",
      "LIVE SYSTEM":"LIVE-SYSTEM","01 — SPEED":"01 — SPEED","02 — CLARITY":"02 — KLARHEIT","03 — REACH":"03 — REICHWEITE","CHOOSE YOUR ROUTE":"WÄHLE DEINE ROUTE","One studio. Separate systems.":"Ein Studio. Separate Systeme.","Selected studio builds across completely different industries.":"Ausgewählte Studio-Builds aus völlig unterschiedlichen Branchen.","OPEN THE FULL GARAGE →":"DIE GANZE GARAGE ÖFFNEN →",
      "CHOOSE THE MACHINE.":"WÄHLE DIE MASCHINE.","PAGES":"SEITEN","LANGUAGES":"SPRACHEN","BOOKING":"BUCHUNG","LOCALIZATION":"LOKALISIERUNG","ACCESSIBILITY":"BARRIEREFREIHEIT","INTEGRATIONS":"INTEGRATIONEN","CARE PLAN":"BETREUUNGSPLAN","DIGITAL SPEC SHEET":"DIGITALES SPEZIFIKATIONSBLATT",
      "DIFFERENT BUSINESS. DIFFERENT MACHINE.":"ANDERES BUSINESS. ANDERE MASCHINE.","Selected studio builds and independent ventures. Status is labelled honestly — no fake client results.":"Ausgewählte Studio-Builds und eigene Ventures. Der Status wird ehrlich gekennzeichnet — keine erfundenen Kundenergebnisse.",
      "SPEAK TO THE WHOLE GRID.":"SPRICH MIT DEM GANZEN GRID.","SIX-LANGUAGE STUDIO":"STUDIO IN SECHS SPRACHEN","QUALITY CONTROL":"QUALITÄTSKONTROLLE","NATIVE / HUMAN QA":"NATIVE / MENSCHLICHE QA","We build and localize websites across all six studio languages.":"Wir bauen und lokalisieren Websites in allen sechs Studiosprachen.","Final commercial copy is reviewed where required before publication. QA is a quality standard, not a language limitation.":"Finale kommerzielle Texte werden bei Bedarf vor Veröffentlichung geprüft. QA ist ein Qualitätsstandard, keine Sprachbeschränkung.",
      "WEBSITE URL":"WEBSITE-URL","BEFORE":"VORHER","AFTER / LAUNCH CTRL":"NACHHER / LAUNCH CTRL","MOVE":"VERSCHIEBEN","KEEP IT TUNED.":"HALT ES ABGESTIMMT.","UPDATES":"UPDATES","SMALL CHANGES":"KLEINE ÄNDERUNGEN","MONITORING":"MONITORING","PAGE ADDITIONS":"NEUE SEITEN","IMPROVEMENTS":"VERBESSERUNGEN","SUPPORT":"SUPPORT","BUILD IT ONCE. KEEP IMPROVING IT.":"EINMAL BAUEN. IMMER WEITER VERBESSERN.","ASK ABOUT PIT CREW":"NACH PIT CREW FRAGEN",
      "NAME":"NAME","BUSINESS":"UNTERNEHMEN","COUNTRY":"LAND","INDUSTRY":"BRANCHE","EXISTING WEBSITE":"BESTEHENDE WEBSITE","WHAT DO YOU NEED?":"WAS BRAUCHST DU?","Select":"Auswählen","APPROX. PAGES":"CA. SEITEN","FUNCTIONALITY":"FUNKTIONEN","DEADLINE":"DEADLINE","BUDGET RANGE":"BUDGETRAHMEN","NOTES":"NOTIZEN","COMPANY WEBSITE":"UNTERNEHMENSWEBSITE",
      "BACK TO LAUNCH CTRL":"ZURÜCK ZU LAUNCH CTRL","PRIVACY":"DATENSCHUTZ","← BACK TO THE GARAGE":"← ZURÜCK ZUR GARAGE","CURRENT STATE / ACTIVE BUILD":"AKTUELLER STAND / AKTIVER BUILD","IN DEVELOPMENT / STUDIO BUILD":"IN ENTWICKLUNG / STUDIO-BUILD","01 / CHALLENGE":"01 / HERAUSFORDERUNG","02 / DIRECTION":"02 / RICHTUNG","03 / SYSTEM":"03 / SYSTEM","04 / LANGUAGES":"04 / SPRACHEN","THE BUSINESS FIRST.":"DAS BUSINESS ZUERST.","NO TEMPLATE LOGIC.":"KEINE TEMPLATE-LOGIK.","WHAT THE BUILD NEEDS TO DO.":"WAS DER BUILD LEISTEN MUSS.","MARKET READY.":"MARKTREIF.","NEXT BUILD":"NÄCHSTER BUILD"
    },
    it: {
      "Skip to content":"Vai al contenuto","HOME":"HOME","BUILDS":"BUILDS","GARAGE":"GARAGE","CROSS-BORDER":"INTERNAZIONALE","REBUILD":"REBUILD","PIT CREW":"PIT CREW","CONTACT":"CONTATTI",
      "LIVE SYSTEM":"SISTEMA LIVE","01 — SPEED":"01 — VELOCITÀ","02 — CLARITY":"02 — CHIAREZZA","03 — REACH":"03 — PORTATA","CHOOSE YOUR ROUTE":"SCEGLI IL PERCORSO","One studio. Separate systems.":"Uno studio. Sistemi separati.","Selected studio builds across completely different industries.":"Build selezionati in settori completamente diversi.","OPEN THE FULL GARAGE →":"APRI TUTTO IL GARAGE →",
      "CHOOSE THE MACHINE.":"SCEGLI LA MACCHINA.","PAGES":"PAGINE","LANGUAGES":"LINGUE","BOOKING":"PRENOTAZIONE","LOCALIZATION":"LOCALIZZAZIONE","ACCESSIBILITY":"ACCESSIBILITÀ","INTEGRATIONS":"INTEGRAZIONI","CARE PLAN":"PIANO DI CURA","DIGITAL SPEC SHEET":"SCHEDA TECNICA DIGITALE",
      "DIFFERENT BUSINESS. DIFFERENT MACHINE.":"BUSINESS DIVERSO. MACCHINA DIVERSA.","Selected studio builds and independent ventures. Status is labelled honestly — no fake client results.":"Build selezionati e progetti indipendenti. Lo stato è indicato onestamente — nessun falso risultato cliente.",
      "SPEAK TO THE WHOLE GRID.":"PARLA A TUTTA LA GRIGLIA.","SIX-LANGUAGE STUDIO":"STUDIO IN SEI LINGUE","QUALITY CONTROL":"CONTROLLO QUALITÀ","NATIVE / HUMAN QA":"QA NATIVA / UMANA","We build and localize websites across all six studio languages.":"Realizziamo e localizziamo siti in tutte e sei le lingue dello studio.","Final commercial copy is reviewed where required before publication. QA is a quality standard, not a language limitation.":"Il copy commerciale finale viene revisionato quando necessario prima della pubblicazione. La QA è uno standard di qualità, non un limite linguistico.",
      "WEBSITE URL":"URL DEL SITO","BEFORE":"PRIMA","AFTER / LAUNCH CTRL":"DOPO / LAUNCH CTRL","MOVE":"SPOSTA","KEEP IT TUNED.":"TIENILO A PUNTO.","UPDATES":"AGGIORNAMENTI","SMALL CHANGES":"PICCOLE MODIFICHE","MONITORING":"MONITORAGGIO","PAGE ADDITIONS":"NUOVE PAGINE","IMPROVEMENTS":"MIGLIORAMENTI","SUPPORT":"SUPPORTO","BUILD IT ONCE. KEEP IMPROVING IT.":"COSTRUISCILO UNA VOLTA. CONTINUA A MIGLIORARLO.","ASK ABOUT PIT CREW":"CHIEDI DI PIT CREW",
      "NAME":"NOME","BUSINESS":"AZIENDA","COUNTRY":"PAESE","INDUSTRY":"SETTORE","EXISTING WEBSITE":"SITO ESISTENTE","WHAT DO YOU NEED?":"DI COSA HAI BISOGNO?","Select":"Seleziona","APPROX. PAGES":"PAGINE APPROX.","FUNCTIONALITY":"FUNZIONALITÀ","DEADLINE":"SCADENZA","BUDGET RANGE":"BUDGET","NOTES":"NOTE","COMPANY WEBSITE":"SITO AZIENDALE",
      "BACK TO LAUNCH CTRL":"TORNA A LAUNCH CTRL","PRIVACY":"PRIVACY","← BACK TO THE GARAGE":"← TORNA AL GARAGE","CURRENT STATE / ACTIVE BUILD":"STATO ATTUALE / BUILD ATTIVO","IN DEVELOPMENT / STUDIO BUILD":"IN SVILUPPO / BUILD STUDIO","01 / CHALLENGE":"01 / SFIDA","02 / DIRECTION":"02 / DIREZIONE","03 / SYSTEM":"03 / SISTEMA","04 / LANGUAGES":"04 / LINGUE","THE BUSINESS FIRST.":"PRIMA IL BUSINESS.","NO TEMPLATE LOGIC.":"NESSUNA LOGICA DA TEMPLATE.","WHAT THE BUILD NEEDS TO DO.":"COSA DEVE FARE IL BUILD.","MARKET READY.":"PRONTO PER IL MERCATO.","NEXT BUILD":"BUILD SUCCESSIVO"
    },
    ru: {
      "Skip to content":"Перейти к содержимому","HOME":"ГЛАВНАЯ","BUILDS":"BUILDS","GARAGE":"ГАРАЖ","CROSS-BORDER":"МЕЖДУНАРОДНО","REBUILD":"REBUILD","PIT CREW":"PIT CREW","CONTACT":"КОНТАКТЫ",
      "LIVE SYSTEM":"LIVE-СИСТЕМА","01 — SPEED":"01 — СКОРОСТЬ","02 — CLARITY":"02 — ЯСНОСТЬ","03 — REACH":"03 — ОХВАТ","CHOOSE YOUR ROUTE":"ВЫБЕРИТЕ МАРШРУТ","One studio. Separate systems.":"Одна студия. Отдельные системы.","Selected studio builds across completely different industries.":"Выбранные studio builds из совершенно разных отраслей.","OPEN THE FULL GARAGE →":"ОТКРЫТЬ ВЕСЬ ГАРАЖ →",
      "CHOOSE THE MACHINE.":"ВЫБЕРИТЕ МАШИНУ.","PAGES":"СТРАНИЦЫ","LANGUAGES":"ЯЗЫКИ","BOOKING":"БРОНИРОВАНИЕ","LOCALIZATION":"ЛОКАЛИЗАЦИЯ","ACCESSIBILITY":"ДОСТУПНОСТЬ","INTEGRATIONS":"ИНТЕГРАЦИИ","CARE PLAN":"ПЛАН ПОДДЕРЖКИ","DIGITAL SPEC SHEET":"ЦИФРОВАЯ СПЕЦИФИКАЦИЯ",
      "DIFFERENT BUSINESS. DIFFERENT MACHINE.":"ДРУГОЙ БИЗНЕС. ДРУГАЯ МАШИНА.","Selected studio builds and independent ventures. Status is labelled honestly — no fake client results.":"Выбранные studio builds и собственные проекты. Статус указан честно — никаких вымышленных результатов клиентов.",
      "SPEAK TO THE WHOLE GRID.":"ГОВОРИТЕ СО ВСЕЙ СЕТКОЙ.","SIX-LANGUAGE STUDIO":"СТУДИЯ НА ШЕСТИ ЯЗЫКАХ","QUALITY CONTROL":"КОНТРОЛЬ КАЧЕСТВА","NATIVE / HUMAN QA":"NATIVE / HUMAN QA","We build and localize websites across all six studio languages.":"Мы создаём и локализуем сайты на всех шести языках студии.","Final commercial copy is reviewed where required before publication. QA is a quality standard, not a language limitation.":"Финальный коммерческий текст при необходимости проверяется перед публикацией. QA — стандарт качества, а не языковое ограничение.",
      "WEBSITE URL":"URL САЙТА","BEFORE":"ДО","AFTER / LAUNCH CTRL":"ПОСЛЕ / LAUNCH CTRL","MOVE":"ДВИГАТЬ","KEEP IT TUNED.":"ДЕРЖИТЕ ЕГО НАСТРОЕННЫМ.","UPDATES":"ОБНОВЛЕНИЯ","SMALL CHANGES":"НЕБОЛЬШИЕ ИЗМЕНЕНИЯ","MONITORING":"МОНИТОРИНГ","PAGE ADDITIONS":"НОВЫЕ СТРАНИЦЫ","IMPROVEMENTS":"УЛУЧШЕНИЯ","SUPPORT":"ПОДДЕРЖКА","BUILD IT ONCE. KEEP IMPROVING IT.":"ПОСТРОЙТЕ ОДИН РАЗ. УЛУЧШАЙТЕ ПОСТОЯННО.","ASK ABOUT PIT CREW":"СПРОСИТЬ О PIT CREW",
      "NAME":"ИМЯ","BUSINESS":"БИЗНЕС","COUNTRY":"СТРАНА","INDUSTRY":"ОТРАСЛЬ","EXISTING WEBSITE":"ТЕКУЩИЙ САЙТ","WHAT DO YOU NEED?":"ЧТО ВАМ НУЖНО?","Select":"Выбрать","APPROX. PAGES":"ПРИМЕРНО СТРАНИЦ","FUNCTIONALITY":"ФУНКЦИИ","DEADLINE":"СРОК","BUDGET RANGE":"БЮДЖЕТ","NOTES":"ЗАМЕТКИ","COMPANY WEBSITE":"САЙТ КОМПАНИИ",
      "BACK TO LAUNCH CTRL":"НАЗАД К LAUNCH CTRL","PRIVACY":"КОНФИДЕНЦИАЛЬНОСТЬ","← BACK TO THE GARAGE":"← НАЗАД В ГАРАЖ","CURRENT STATE / ACTIVE BUILD":"ТЕКУЩИЙ СТАТУС / АКТИВНЫЙ BUILD","IN DEVELOPMENT / STUDIO BUILD":"В РАЗРАБОТКЕ / STUDIO BUILD","01 / CHALLENGE":"01 / ЗАДАЧА","02 / DIRECTION":"02 / НАПРАВЛЕНИЕ","03 / SYSTEM":"03 / СИСТЕМА","04 / LANGUAGES":"04 / ЯЗЫКИ","THE BUSINESS FIRST.":"СНАЧАЛА БИЗНЕС.","NO TEMPLATE LOGIC.":"БЕЗ ШАБЛОННОЙ ЛОГИКИ.","WHAT THE BUILD NEEDS TO DO.":"ЧТО ДОЛЖЕН ДЕЛАТЬ BUILD.","MARKET READY.":"ГОТОВО К РЫНКУ.","NEXT BUILD":"СЛЕДУЮЩИЙ BUILD"
    }
  };

  const sourceText = new WeakMap();
  const sourceAttr = new WeakMap();

  function remember() {
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let n;
    while ((n = walker.nextNode())) {
      const p = n.parentElement;
      if (!p || /^(SCRIPT|STYLE|NOSCRIPT)$/.test(p.tagName)) continue;
      const raw = n.nodeValue;
      const trimmed = raw.trim();
      if (trimmed) sourceText.set(n, {raw, trimmed});
    }
    document.querySelectorAll('[placeholder]').forEach(el => sourceAttr.set(el, el.getAttribute('placeholder')));
  }

  function applyLiteral(lang) {
    const dict = T[lang] || {};
    for (const [node, src] of sourceText) {
      const next = lang === 'en' ? src.trimmed : (dict[src.trimmed] || src.trimmed);
      const lead = src.raw.match(/^\s*/)?.[0] || '';
      const tail = src.raw.match(/\s*$/)?.[0] || '';
      node.nodeValue = lead + next + tail;
    }
    document.querySelectorAll('[placeholder]').forEach(el => {
      const src = sourceAttr.get(el) || el.getAttribute('placeholder') || '';
      el.setAttribute('placeholder', lang === 'en' ? src : (dict[src] || src));
    });
  }

  remember();
  const saved = localStorage.getItem('launchCtrlLang') || document.documentElement.lang || 'en';
  applyLiteral(saved);
  document.querySelectorAll('.lang').forEach(btn => btn.addEventListener('click', () => {
    setTimeout(() => applyLiteral(btn.dataset.lang || 'en'), 0);
  }));
  window.launchCtrlApplyLiteral = applyLiteral;
})();